version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: keycloakuser
      POSTGRES_PASSWORD: 2510
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloakdb
      DB_USER: keycloakuser
      DB_PASSWORD: 2510

      KC_HOSTNAME_ADMIN: localhost
      KC_PROXY: edge
      KC_HOSTNAME: some-machine.somewhere
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_DB: postgres
      KC_DB_PASSWORD: 2510
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloakuser
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_LOG_LEVEL: ALL


    ports:
      - "8080:8080"
    command: start-dev
    depends_on:
      - postgres

volumes:
  postgres_data:
